version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
    # Enables hot reload by mapping workdir to container workdir
      - ./:/usr/src/smart-brain-api
    environment:
        POSTGRES_DB: smart_brain_docker
        POSTGRES_USER: dementedearplug
        POSTGRES_PASSWORD: incorrect
        POSTGRES_HOST: database
    links:
      - database
  #Adding postgress
  database:
    build: postgres
    environment:
        POSTGRES_DB: smart_brain_docker
        POSTGRES_USER: dementedearplug
        POSTGRES_PASSWORD: incorrect
        POSTGRES_HOST: database
    ports:
      - "5432:5432"

